# standup example config

["standup.providers.asana"]
enabled = false
api_key = ""

["standup.providers.github"]
enabled = false
api_key = "XXX"

["standup.providers.jira"]
enabled = false
api_key = "XXX"
