# Standup Configuration
# ---
# NOTE: secrets are only read from the environment.

["standup.providers.asana"]
enabled = true
env_token = "ASANA_TOKEN"
env_user = "ASANA_USER"
env_workspace = "ASANA_WORKSPACE"

["standup.providers.github"]
enabled = false
env_api_key = "GITHUB_TOKEN"

["standup.providers.jira"]
enabled = false
env_api_key = "JIRA_TOKEN"
