# Standup Configuration
# ---
# NOTE: secrets are only read from the environment.

["standup.providers.asana"]
enabled = false
env_api_key = "ASANA_env_api_key"

["standup.providers.github"]
enabled = false
env_api_key = "GITHUB_TOKEN"

["standup.providers.jira"]
enabled = false
env_api_key = "JIRA_TOKEN"
